# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="RIXED"
DIST_VERSION="1.21"


inherit perl-module

DESCRIPTION="Parse iCalendar files into a data structure"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=">=dev-perl/DateTime-Format-ICal-0.90.0
	>=dev-perl/Text-vFile-asData-0.80.0
	>=dev-perl/FreezeThaw-0.500.100
	dev-perl/IO-String
	dev-lang/perl"
